[versions]
androidGradlePlugin = "7.4.2"
kotlin = "1.8.10"
ksp = "1.8.10-1.0.9"
aboutlibraries = "10.6.2"
androidDesugarJDKLibs = "2.0.2"
room = "2.5.1"
lifecycle = "2.6.1"
navigationUI = "2.5.3"
splitties = "3.0.0"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.5.0" }
android-desugarJDKLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJDKLibs" }
material = { module = "com.google.android.material:material", version = "1.8.0" }
ini4j = { module = "org.ini4j:ini4j", version = "0.5.4" }
autofill = { module = "androidx.autofill:autofill", version = "1.1.0" }
arrow = { module = "io.arrow-kt:arrow-core", version = "1.1.5" }
activity = { module = "androidx.activity:activity-ktx", version = "1.7.0" }
imagecropper = { module = "com.vanniktech:android-image-cropper", version = "4.5.0" }
flexbox = { module = "com.google.android.flexbox:flexbox", version = "3.0.0" }
dependency = { module = "org.mechdancer:dependency", version = "0.1.2" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
core-ktx = { module = "androidx.core:core-ktx", version = "1.9.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.6.4" }
preference = { module = "androidx.preference:preference-ktx", version = "1.2.0" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.0" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version = "1.0.0" }
paging = { module = "androidx.paging:paging-runtime-ktx", version = "3.1.1" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUI" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUI" }
splitties-bitflags = { module = "com.louiscad.splitties:splitties-bitflags", version.ref = "splitties" }
splitties-systemservices = { module = "com.louiscad.splitties:splitties-systemservices", version.ref = "splitties" }
splitties-views-dsl = { module = "com.louiscad.splitties:splitties-views-dsl", version.ref = "splitties" }
splitties-views-dsl-constraintlayout = { module = "com.louiscad.splitties:splitties-views-dsl-constraintlayout", version.ref = "splitties" }
splitties-views-dsl-recyclerview = { module = "com.louiscad.splitties:splitties-views-dsl-recyclerview", version.ref = "splitties" }
splitties-views-dsl-material = { module = "com.louiscad.splitties:splitties-views-dsl-material", version.ref = "splitties" }
splitties-views-recyclerview = { module = "com.louiscad.splitties:splitties-views-recyclerview", version.ref = "splitties" }
aboutlibraries = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibrariesPlugin = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "aboutlibraries" }
junit = { module = "junit:junit", version = "4.13.2" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.5.2" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.5.0" }
lifecycle-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "lifecycle" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version = "1.12.0" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }